#!/bin/sh

#
# This file simply redirects all passed arguments
# to checkers.inference.InferenceLauncher
#

myDir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      myDir=`cygpath -m $mydir`
      ;;
esac

if [ "$myDir" = "" ];
then
    myDir=$(pwd)
fi

ROOT=$(cd ${myDir}/../../ >/dev/null 2>&1 && pwd)

distDir=$myDir"/../dist"

libDir=$myDir"/../lib"

classpath="$distDir"/checker.jar:"$distDir"/annotation-file-utilities.jar:"$distDir"/checker-framework-inference.jar

if [ "$external_checker_classpath" != "" ] ; then
    classpath=${classpath}:${external_checker_classpath}
fi

export DYLD_LIBRARY_PATH=${libDir}
export LD_LIBRARY_PATH=${libDir}

runtimeBCP=""
java -version 2>&1 | grep version | grep 1.8 > /dev/null
if [ $? -eq 0 ]; then
    runtimeBCP="${distDir}/javac.jar"
fi

# use default "pathToAfuScripts" unless specified
defaultPathToAfuScripts="--pathToAfuScripts=${ROOT}/annotation-tools/annotation-file-utilities/scripts"
for arg in "$@"
do
    case "$arg" in
        --pathToAfuScripts=*) defaultPathToAfuScripts="" ;;
    esac
done

eval "java -DInferenceLauncher.runtime.bcp="$runtimeBCP" -classpath "$classpath" checkers.inference.InferenceLauncher " \
 "$defaultPathToAfuScripts" "$@"
